/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui4;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author wiech
 */
public class Pesel extends javax.swing.JFrame {

    /**
     * Creates new form Pesel
     */
    public Pesel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        przycisk = new javax.swing.JButton();
        wynik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peselActionPerformed(evt);
            }
        });

        jLabel1.setText("Wpisz numer pesel:");

        przycisk.setText("Sprawdź");
        przycisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskActionPerformed(evt);
            }
        });

        wynik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wynik.setText("Czy pesel jest prawidlowy?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(przycisk)
                            .addComponent(pesel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(wynik, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addComponent(przycisk)
                .addGap(59, 59, 59)
                .addComponent(wynik)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


     public boolean weryfikacja(String peselnr) {
         if(pesel.getText().length()!=11)
         {return false;}
        int sum = 0;
        int temp = 0;
        int waga[] = {1, 3, 7, 9, 1, 3, 7, 9, 1, 3};
        int x = 0;

        for (int i = 0; i < pesel.getText().length() - 1; i++) {
            temp = Character.getNumericValue(pesel.getText().charAt(i));
            sum += (temp * waga[i]);
        }

        x = 10 - (sum % 10);
        x = x % 10;
        
        if (x == Character.getNumericValue(pesel.getText().charAt(10))) {
            return true;
            
        } else {
            return false;
        }
    }
    
    public void pliczek(String peselnr)throws IOException{
        File file = new File("Pesel.txt");

        try {
            if (!file.exists())
                file.createNewFile();

            PrintWriter out =new PrintWriter(new BufferedWriter(new FileWriter(file, true)));
            out.append(pesel.getText());
            out.append("  \n ");
            out.close();

        } catch (Exception e) {
        }
    }

    

    private void peselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peselActionPerformed

    private void przyciskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskActionPerformed
  if (weryfikacja(pesel.getText())) {
      try {
          wynik.setText("Wprowadzony PESEL to: " + pesel.getText());
          pliczek(pesel.getText());
      } catch (IOException ex) {
          Logger.getLogger(Pesel.class.getName()).log(Level.SEVERE, null, ex);
      }
                    
                }

                else
                    wynik.setText("Wprowadzony PESEL jest błędny");
        
    }//GEN-LAST:event_przyciskActionPerformed
                               
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField pesel;
    private javax.swing.JButton przycisk;
    private javax.swing.JLabel wynik;
    // End of variables declaration//GEN-END:variables
}
